<?php
/**
 * TL_ROOT/system/modules/gallery_creator/languages/de/modules.php
 *
 * Contao extension: gallery_creator 5.0.0
 * Deutsch translation file
 *
 * Copyright : &copy; 2015 Marko Cupic
 * License   : GNU Lesser Public License (LGPL)
 * Author    : Marko Cupic (markocupic)
 * Translator: Marko Cupic (markocupic)
 *
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

$GLOBALS['TL_LANG']['MOD']['office365']['0'] = "Office 365 Tools";
$GLOBALS['TL_LANG']['MOD']['office365_member']['0'] = "Office 365 Konten";
$GLOBALS['TL_LANG']['MOD']['office365_member']['1'] = "Office 365 Konten administrieren";


